const moment = require('moment-timezone') 
 const {fetchJson,cmd, tlang } = require('../lib') 
 let gis = require("async-g-i-s"); 
 const axios = require('axios');
 const fetch = require('node-fetch');
 const Esana = require('@sl-code-lords/esana-news') 
 var api = new Esana() 

//---------------------------------------------------------------------------

cmd({ 
         pattern: "esana", 
         category: "news",
         react: "📃",
         desc: "Searches news", 
         use: '<text>', 
         filename: __filename, 
     }, 
     async(Void, citel) => { 
        let res = await api.latest_id(); 
        const nid = res.results.news_id; 
        let news = await api.news(nid); 
        const tt = news.results.TITLE; 
        const dss = news.results.DESCRIPTION; 
        const ttime = news.results.PUBLISHED; 
        const img = news.results.COVER; 
        const cap = `📃ＮＥＷＳ ＢＹ ＶＡＪＩＲＡ\n\n◉───────────────\n🏷️ ᴛɪᴛʟᴇ➨ ${tt}\n◉───────────────\n 🕒 ᴛɪᴍᴇ➨ ${ttime}\n◉─────────────── \n 📑 ᴅᴇꜱᴄʀɪᴘᴛɪᴏɴ➨ ${dss}\n◉─────────────── \n\n ▶.GENERATED BY VAJIRA.◀`; 
                 await Void.sendMessage(citel.chat,{image:{url: img}, caption: cap})
 })
